export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_EPISODES = 'GET_EPISODES';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const FILTER_CHARACTERS = 'FILTER_CHARACTERS';
export const FILTER_EPISODE = 'FILTER_EPISODE';
export const FILTER_LOCATIONS = 'FILTER_LOCATIONS';
